FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore

COPY . ./
RUN dotnet publish ./consumer-portal-backend.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine3.9
WORKDIR /consumer-portal-backend
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","consumer-portal-backend.dll"]
